#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version

In [5]:
np.__version__

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [17]:
a = np.zeros(10)
a.astype(np.float64)
a.dtype

dtype('float64')

In [ ]:
#Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
arr[arr<4]

array([1, 2, 3])

#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
a2 = np.arange(10,50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
a2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [92]:
np.flipud(a2)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
a3 = np.arange(0,9)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a3.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [121]:
a4 = np.array([1,2,0,0,4,0])
a4[(a4>0)]


array([1, 2, 4])

In [133]:

n= np.array([1,2,0,0,4,0])
x = np.where(n != 0)[:]
print(x)

(array([0, 1, 4]),)


In [99]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
 np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [138]:
np.random.rand(3,3,3)

array([[[0.25127351, 0.03950604, 0.89321307],
        [0.25663324, 0.1061068 , 0.61626617],
        [0.64351999, 0.55380659, 0.78137041]],

       [[0.29339869, 0.14851572, 0.67139831],
        [0.13305287, 0.46666081, 0.51684908],
        [0.11713484, 0.8178169 , 0.33620731]],

       [[0.83886739, 0.40782051, 0.58510233],
        [0.25559024, 0.0815784 , 0.24677093],
        [0.88011732, 0.70168527, 0.73862758]]])

In [147]:
np.random.randint(1,100,(3,3,3))

array([[[60, 67, 24],
        [55, 16, 24],
        [ 9, 27, 59]],

       [[77, 16, 43],
        [75, 48, 24],
        [53, 41, 30]],

       [[ 1, 98, 20],
        [49, 41, 44],
        [31, 73, 33]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
a13 = np.random.rand(10,10)
print(a13.max())
print(a13.min())

0.9984974979391792
0.0068144025373672035


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [36]:
x = np.random.random(10)
x.mean()

0.5704619221139773

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [72]:
a15 = np.ones((3,3))
a15[1:-1,1:-1] = 0
a15

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [4]:
#Ghost ans for no.16
mat = np.arange(1,26).reshape(5,5)
mat[:,::4] = 0
mat[::4] = 0
mat

array([[ 0,  0,  0,  0,  0],
       [ 0,  7,  8,  9,  0],
       [ 0, 12, 13, 14,  0],
       [ 0, 17, 18, 19,  0],
       [ 0,  0,  0,  0,  0]])

In [89]:
mat

array([[ 0,  0,  0,  0,  0],
       [ 0,  7,  8,  9,  0],
       [ 0, 12, 13, 14,  0],
       [ 0, 17, 18, 19,  0],
       [ 0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [6]:

0.3 == 3 * 0.1  # ans = false coz 3*0.1 gives some decimal value so it is false

False

In [7]:
0 * np.nan #nan is nan whatsoever

nan

In [8]:
np.nan == np.nan #diff nan has diff values maybe

False

In [10]:
np.inf < np.nan # cant compare infinity with nothing ryt

False

In [11]:
np.nan - np.nan # nan

nan

In [12]:
np.nan in set([np.nan])

True

#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

In [34]:
a18 = np.arange(0,16).reshape(4,4)
m = np.array([0,1,2])[np.newaxis]
m= m.T
a18[1:,:1] = m
a18[3,1] = 3
a18

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 1,  9, 10, 11],
       [ 2,  3, 14, 15]])

In [17]:
a18 = np.arange(0,16).reshape(4,4)
print(a18,end="\n")
aas = np.diag(a18,-1)
aas = [0,1,2,3]
aas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[0, 1, 2, 3]

In [23]:
a18 = np.diag(np.arange(4),-1)
a18

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
---



In [24]:
a19 = np.zeros(10)
a19[4]=5
a19

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 22. Normalize a 5x5 random matrix (★☆☆) Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X [link text](https://)

In [33]:
x= np.random.random((3,3))
print("Original Array:")
print(x,end="\n\n\n")
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.89693837 0.28653148 0.62436715]
 [0.36621425 0.46924415 0.02347333]
 [0.42444355 0.45557912 0.77870471]]


After normalization:
[[1.         0.3011662  0.68794261]
 [0.39239226 0.51034763 0.        ]
 [0.45905697 0.49470301 0.86463836]]


In [34]:
a22 = np.random.randint(0,100,(5,5))
amean = a22.max()
astd = a22.min()
val = (a22-astd)/(amean - astd)
val

array([[0.91397849, 0.11827957, 0.92473118, 0.77419355, 0.23655914],
       [0.37634409, 1.        , 0.7311828 , 0.16129032, 0.83870968],
       [0.44086022, 0.22580645, 0.7311828 , 0.52688172, 0.09677419],
       [0.94623656, 0.20430108, 0.19354839, 0.52688172, 0.05376344],
       [0.41935484, 0.10752688, 0.97849462, 0.74193548, 0.        ]])

#### 23. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [38]:
a23 = np.array([[1, 2 ,3], [4, 5, 6]])
a23[a23<4]

array([1, 2, 3])

#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
x1 = np.arange(0,15).reshape(5,3)

In [41]:
x2 = np.arange(0,6).reshape(3,2)

In [45]:
print(x1.dot(x2))
print("\n")
print(np.dot(x1,x2))


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Consider two random array A and B, check if they are equal (★★☆)

In [4]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([0,1,2,3,4,5,6,7,8,9])
if np.allclose(a,b):
    print(True)

True


#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
a26 = np.array([0,1,2,3,4,5,6,7,8,9])
max=a26.max()
a26[a26.argmax()] = 0
a26

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 27. Subtract the mean of each row of a matrix (★★☆):

In [64]:
x1 = np.arange(0,15).reshape(5,3)

In [65]:
np.std(x1,axis = 1)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [3]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
z = np.std(X , axis=1)
print(Y)
print(z)

Original matrix:

[[3.62348912e-01 8.49154773e-02 4.51232470e-01 2.63495812e-01
  1.82882932e-01 5.06165834e-01 1.37354416e-01 5.49708103e-01
  2.92330498e-02 2.33299369e-01]
 [2.34626655e-01 3.74168131e-01 5.72032793e-01 1.67575403e-01
  4.14451611e-01 8.19523891e-01 8.32446394e-01 6.87339061e-01
  1.05160242e-01 6.57322772e-01]
 [7.18751317e-01 1.62455909e-02 7.17951488e-01 8.84215569e-01
  3.08801705e-01 3.49417340e-01 4.36814655e-01 7.93433679e-01
  2.09916498e-01 3.91236445e-01]
 [9.21124270e-01 2.09745656e-01 1.13106909e-01 1.37174956e-01
  8.95668158e-02 8.29333549e-01 5.34117246e-01 2.49448937e-01
  3.34541238e-01 7.22540439e-01]
 [5.55018531e-01 4.57226691e-01 1.89312239e-02 3.52185091e-04
  8.41318835e-01 3.85932697e-01 9.67102122e-02 6.54402162e-01
  2.32426774e-01 6.09365942e-01]]

Subtract the mean of each row of the said matrix:

[[ 0.08228527 -0.19514816  0.17116883 -0.01656783 -0.09718071  0.2261022
  -0.14270922  0.26964447 -0.25083059 -0.04676427]
 [-0.25183804 -0.112